# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-22 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='wished_for_by',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='liked_wishes', to='wish_app.User'),
            preserve_default=False,
        ),
    ]
