# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-15 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semirestful_app', '0002_remove_restful_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restful',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
