# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-15 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semirestful_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restful',
            name='action',
        ),
    ]
