# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semirestful_app', '0004_auto_20190915_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='restful',
            name='description',
            field=models.TextField(default='Add Description here'),
            preserve_default=False,
        ),
    ]
